import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { AuthProvider } from "@/util/context/AuthContext";
import { ToastContainer } from "react-toastify";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ToastContainer
          position="bottom-right" // 🔹 Đặt ở góc dưới bên phải
          autoClose={3000} // 🔹 Tự động đóng sau 3s
          hideProgressBar={false} // 🔹 Hiển thị thanh tiến trình
          newestOnTop={false} // 🔹 Không ưu tiên toast mới nhất lên trên
          closeOnClick // 🔹 Đóng khi click
          rtl={false} // 🔹 Không dùng chế độ RTL
          pauseOnFocusLoss // 🔹 Tạm dừng khi mất focus
          draggable // 🔹 Kéo thả toast
          pauseOnHover // 🔹 Tạm dừng khi hover
          theme="light" // 🔹 Đặt theme light (hoặc "dark")
        />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
